site_name: MCW MSTP Code
site_url: httpe://www.google.com
repo_url: https://github.com/mcw-mstp/mcw-mstp

nav:
    - Home: 
        - Welcome: index.md
        - News: news.md
    - Singe Cell Seq: single_cell.md
    - Resources: resources.md
    - People: people.md
    - Contributing: contributing.md

theme: 
  name: material
  custom_dir: overrides
  features:
    - navigation.tabs

markdown_extensions:
  - abbr
  - admonition
  - meta
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mcw-mstp